//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicitatiiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cumparator : Utilizator
    {
        public Cumparator()
        {
            this.Produs = new HashSet<Produs>();
        }
    
        public string CNP { get; set; }
        public string Telefon { get; set; }
    
        public virtual ICollection<Produs> Produs { get; set; }
    }
}
