//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicitatiiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produs
    {
        public int Id { get; set; }
        public string Nume { get; set; }
        public string Descriere { get; set; }
        public decimal PretDeInceput { get; set; }
        public Nullable<decimal> PretLicitat { get; set; }
        public System.DateTime DataDeInceput { get; set; }
        public System.DateTime DataDeSfarsit { get; set; }
        public int VanzatorId { get; set; }
        public int CumparatorId { get; set; }
    
        public virtual Vanzator Vanzator { get; set; }
        public virtual Cumparator Cumparator { get; set; }
    }
}
